jaffle_shop:
  outputs:
    dev:
      dataset: dbt_demo_jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/samir.liu/Documents/Vpon/dbt/SA_de-scc-org-sandbox_dbt-user.json
      location: US
      method: service-account
      priority: interactive
      project: de-scc-org-sandbox
      threads: 1
      type: bigquery
  target: dev
